import React from 'react';
import TagButton from '../../../Components/TagButton/TagButton';
import image from '../../../../assets/women-2.png';
import TrustSection from '../TrustSection/TrustSection';

function Hero() {
  return (
    <div className="flex h-screen">
      <div className="hero bottom-30 rounded-r-4xl absolute bg-white pl-10">
        <div className="title pr-5">
          <div className="m-4 flex items-center gap-2">
            <TagButton title="skincare" />
            <p className="text-black">Unlocking your best skin</p>
          </div>
          <Title name="Instant Beauty" />
          <Title name="Book Online" />
        </div>
      </div>
      <img
        src={image}
        alt="a chinese women generated by AI"
        className="w-3xl absolute bottom-20 right-0"
      />
      <TrustSection />
    </div>
  );
}

export default Hero;

const Title = ({ name = 'Title' }) => {
  return (
    <>
      <h2 className="leading-20 text-6xl font-extrabold uppercase text-black">
        {name}
      </h2>
    </>
  );
};
