import React from 'react'
import TagButton from '../TagButton/TagButton'
import image from '../../../assets/women-2.png'
import TrustSection from '../TrustSection/TrustSection'

function Hero() {
  return (
    <div className="h-screen flex">
      <div className="hero absolute bottom-30 rounded-r-4xl bg-white pl-10">
        <div className="title pr-5">
          <div className="m-4 flex items-center gap-2">
            <TagButton title="skincare" />
            <p className="text-black">Unlocking your best skin</p>
          </div>
          <Title name="Instant Beauty" />
          <Title name="Book Online" />
        </div>
          </div>
          <img src={image} alt="a chinese women generated by AI" className='absolute right-0 bottom-20 w-3xl' />
          <TrustSection/>
    </div>
  )
}

export default Hero

const Title = ({ name = 'Title' }) => {
  return (
    <>
      <h2 className="text-6xl leading-20 font-extrabold text-black uppercase">
        {name}
      </h2>
    </>
  )
}
